#include <iostream>
using namespace std;

int main(){
    cout << "                                 __.--.._,-'\"\"-." << endl;;
    cout << "                              ,-' .' ,'  .-\"''-.`.       .--." << endl;;
    cout << "                            ,'    |  |  '`-.    \\ \\       `-.|" << endl;;
    cout << "                           /       .   /    `.   \\ \\        ||" << endl;;
    cout << "                          /         `..`.    `.   \\ .       ||" << endl;;
    cout << "                         /        . .    `.    \\   . .      '." << endl;;
    cout << "                .\"-.    .  ,\"\"'-. | |      \\    \\   `.`.__,'.'" << endl;;
    cout << "                 `. `. .   |     `. |       \\    .    `-..-'" << endl;;
    cout << "       _______     .  `|   |   '   .'        .   |...--._" << endl;;
    cout << "       `.     `\"--.'   '    .      | .        .  |\"\"''\"-._\"-._" << endl;;
    cout << "         `.             \\    `-._..'. .       |  |---.._  `-.__\"-.." << endl;;
    cout << "    -.     `.           |\\           `.`      |  |'`-.  `-._   +\"-'" << endl;;
    cout << "    `.`.     `-.        | `            .`.       | `. `.    `,\"" << endl;;
    cout << "      `.`.      `.      |  '.           ` `      `.  \\  `   /" << endl;;
    cout << "      | `.`.    __`.    |`/  `.     ...  `.`.     |   `.   ." << endl;;
    cout << "      |   \\ .  `._      | `. / `. .'.' |   \\ \\    |     \\  |" << endl;;
    cout << "      |.   ` \\    `-.   |   \\   .'.'/' |    \\ \\   |      ._'" << endl;;
    cout << "      | `.  `.\\      `. |    \\ / , '.  |_    . \\  '-." << endl;;
    cout << "     ,     .  .\\       `|     . ' / |  | `-...\\ \\'   `._" << endl;;
    cout << "     `.     `.  \\       |.    '/ .  |  |       ' .      `-." << endl;;
    cout << "      .`._    \\` \\      | `. /'  '  |  |       | |       ,.'" << endl;;
    cout << "       .  `-.  \\`.\\    ,|   //  '   |  |__  .' | |      |" << endl;;
    cout << "       |     `._`| `--' `  //  .    |  '  `\"  /| |   . -'" << endl;;
    cout << "       '        `|       `//   '    |   .    / | |   |" << endl;;
    cout << "      /....._____|       //   .  ___|   |   /  | |  ,|" << endl;;
    cout << "     .         _.'      /, _.--\"'-._ `\".| ,'   | |.'" << endl;;
    cout << "     |      _,' / ___   `-'.        `. _|'     |," << endl;;
    cout << "     |  _,-\"  ,'.'   `-.._  `.      _,'         `" << endl;;
    cout << "     '-\"   _,','          \"- ....--'" << endl;;
    cout << "    /  _.-\"_.'" << endl;;
    cout << "   /_,'_,-'" << endl;;
    cout << " .'_.-'" << endl;;
    cout << " '\"" << endl;;
    
    cout << "                                   ,--.." << endl;
    cout << "                                  /     `." << endl;
    cout << "                                 /|       `." << endl;
    cout << "                                / |        |" << endl;
    cout << "                               /  j        |" << endl;
    cout << "                              /  |         `" << endl;
    cout << "                             '  ,'          \\" << endl;
    cout << "                           ,'                L" << endl;
    cout << "                          /                  +" << endl;
    cout << "                        .:.                   .`" << endl;
    cout << "                     ,\"`.  `.       ,..-._    +" << endl;
    cout << "                     |  |`.  L     '   _.'`.   ." << endl;
    cout << "                     j  `.,\\ '    | ,.' |  +.  +" << endl;
    cout << "                    '`.    |,'    |\" `\"\"   / `, ." << endl;
    cout << "                   |   `\"\"'/      `-.____.'    \\|" << endl;
    cout << "                 ,'|     ,'                     Y" << endl;
    cout << "                /  |    /                      '|" << endl;
    cout << "               /   |  ,'                     ,' +" << endl;
    cout << "              /    \\-'                      /    `" << endl;
    cout << "             /    /                       ,'      `" << endl;
    cout << "            .     ,`'-.                 ,'         L" << endl;
    cout << "             \\   /     \\               /            ." << endl;
    cout << "                /      `               \\            |" << endl;
    cout << "              `/          _,            `          ,'" << endl;
    cout << "               |                         `       ,'" << endl;
    cout << "               |           \"'             `.   ,'" << endl;
    cout << "               j         -\"'               |`-'" << endl;
    cout << "              /                           /'/" << endl;
    cout << "             /           ,               / /" << endl;
    cout << "            /            '              j /" << endl;
    cout << "          .' ___                        '/" << endl;
    cout << "          |-'   `\"`-.                  '/" << endl;
    cout << "          '          \\                .'" << endl;
    cout << "        ,\"            l          _,.-'" << endl;
    cout << "       ,---..         |L     _.-'" << endl;
    cout << "     ,'      `.      / |  ,-'" << endl;
    cout << "    /          `  _,'  ;-'" << endl;
    cout << "  ,'--.       ,-`|  ,-'" << endl;
    cout << " /     L   _,'  _|-'" << endl;
    cout << "(       \\-' _,-'" << endl;
    cout << " `......^.-'   " << endl;
    cout << "" << endl;
    cout << "" << endl;
    
    
    cout << "             SSSSs " << endl;
    cout << "              SSSSs " << endl;
    cout << "           S a a SS " << endl;
    cout << "           '  -  DS " << endl;
    cout << "            \\_= (S " << endl;
    cout << "              _\\SS. " << endl;
    cout << "             (  \\ \\ " << endl;
    cout << "            / \\  \\| " << endl;
    cout << "           |   >  )\\ " << endl;
    cout << "           |_ /  /|/ " << endl;
    cout << "            |/O_/] " << endl;
    cout << "          __|/)___\\_ " << endl;
    cout << "         /__/|\\____/| " << endl;
    cout << "         \\         || " << endl;
    cout << "          \\________|/ " << endl;
    cout << "            |____,_| " << endl;
    cout << "             %%%%% " << endl;
    cout << "              %%%% " << endl;
    cout << "               %%%% " << endl;
    cout << "                %%% " << endl;
    cout << "                %%% " << endl;
    cout << "                %%' " << endl;
    cout << "                %% " << endl;
    cout << "               / O) " << endl;
    cout << "            ,___/\\(    " << endl;
    
    cout << "                                             ,-." << endl;
    cout << "                                          _.|  '" << endl;
    cout << "                                        .'  | /" << endl;
    cout << "                                      ,'    |'" << endl;
    cout << "                                     /      /" << endl;
    cout << "                       _..----\"\"---.'      /" << endl;
    cout << " _.....---------...,-\"\"                  ,'" << endl;
    cout << " `-._  \\                                /" << endl;
    cout << "     `-.+_            __           ,--. ." << endl;
    cout << "          `-.._     .:  ).        (`--\"| \\" << endl;
    cout << "               7    | `\" |         `...'  \\" << endl;
    cout << "               |     `--'     '+\"        ,\". ,\"\"-" << endl;
    cout << "               |   _...        .____     | |/    '" << endl;
    cout << "          _.   |  .    `.  '--\"   /      `./     j" << endl;
    cout << "         \\' `-.|  '     |   `.   /        /     /" << endl;
    cout << "         '     `-. `---\"      `-\"        /     /" << endl;
    cout << "          \\       `.                  _,'     /" << endl;
    cout << "           \\        `                        ." << endl;
    cout << "            \\                                j" << endl;
    cout << "             \\                              /" << endl;
    cout << "              `.                           ." << endl;
    cout << "                +                          \\" << endl;
    cout << "                |                           L" << endl;
    cout << "                |                           |" << endl;
    cout << "                |  _ /,                     |" << endl;
    cout << "                | | L)'..                   |" << endl;
    cout << "                | .    | `                  |" << endl;
    cout << "                '  \\'   L                   '" << endl;
    cout << "                 \\  \\   |                  j" << endl;
    cout << "                  `. `__'                 /" << endl;
    cout << "                _,.--.---........__      /" << endl;
    cout << "               ---.,'---`         |   -j\"" << endl;
    cout << "                .-'  '....__      L    |" << endl;
    cout << "              \"\"--..    _,-'       \\ l||" << endl;
    cout << "                  ,-'  .....------. `||'" << endl;
    cout << "               _,'                /" << endl;
    cout << "             ,'                  /" << endl;
    cout << "            '---------+-        /" << endl;
    cout << "                     /         /" << endl;
    cout << "                   .'         /" << endl;
    cout << "                 .'          /" << endl;
    cout << "               ,'           /" << endl;
    cout << "             _'....----\"\"\"\"\" mh" << endl;
}